sudo: required
services:
- docker
branches:
  only:
  - master
  - develop
script:
- export ENV_FILE=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "prod"; else echo
  "stage"; fi`
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ];  then echo "production"; elif [
  "$TRAVIS_BRANCH" == "develop" ]; then echo "stage"; else echo "dev-$(git rev-parse
  --short HEAD)"; fi`
- docker build --no-cache -t jincort/starflow-ico-dashboard-develop:${TAG} .
- docker run --rm -v $(pwd):/usr/src/app jincort/starflow-ico-dashboard-develop:${TAG}
  /bin/sh -c "yarn && cp -r .env.${ENV_FILE} .env && yarn build && yarn run lint &&
  yarn run test:CI"
after_success:
- export DOCKERFILE=`if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "Dockerfile.stage";
  else echo "Dockerfile.prod" ; fi`
- docker build -f $DOCKERFILE --no-cache -t jincort/starflow-ico-dashboard:${TAG}
  .
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push jincort/starflow-ico-dashboard-develop:${TAG}
- docker push jincort/starflow-ico-dashboard:${TAG}
notifications:
  slack:
    secure: UnHtJGuKp3YhTDfT+wxUTpKcLNHDBG2n5v6urphBqymZT6krG8uFRfh1IJmL72PZaofaPSQYFjU0uYu6rlp6O04ddzTjSYpw2becEX3fGPn96Sw5daSps8V36pxbsyaHf800GiaS3kBFYnrqP8G37TBaXqH51MPH1sKMc0I9+4rmU29E7BOOBRAzcRVbdWEM/MUJFq8RfNEatvOck4D4dLy9q4/ifVutDU++/+Rtcz3NLezcVyKWx7tw8rxJ0FIlqsVPp4QgtE4WRSiru12BS3JuZctzQbMJnARjuOxZEFdMNLn6xVe0FiLRSkHU0c3EpPJJkM3gIlKNmtPA+gltIi/dX3Iq6YqQOLzcVdT9HGv2zRyXH6OafA7pX7BIvCSOniEE/Ktl/NLj6s+jZouW6I0abD8xBTD6/QVX+xBw7htKT5P0xNUJ16dujt9B1nIpwv/D5dor/E6rJeF6bgM1+zWy7lzJY8moZuqQtt3WI01Ig6usMLr5SgoFJIgvWGHPeH3qjhFZLCun+3UU6qtETEa6a6VHtTOrNwYPby6c9B90D/BWABySWiQ3+xyj6S4AlAZqOSPBdsLu2Eg3hQo1caIrby0XVJ1bzfRMXeUdeHvu/9NPmw4ylXsCWBkg/FPeDHmz9mrVkFYWp2UPr6SKDIGvh/zS0vylfNCyfM1k+9Q=
env:
  global:
  - secure: jRZ/K+1xsmwRjg3ufCHTA/FwP1FrT4YlF57fbhM3bP1gU5oy4IO4WmB6u7KVT1p8UkoGkzlInb/qMStPsCvW0MnA2mQZbf7KKpt69G5ETHfoanhFzhaUV6yT3IUeZmun/L+WU1jC4L/mqm2vVShvbNiLEFTsqJpFCjDwdy4SrcCNSEpnGxxveZ9wqBDqAmPcerPj18QbRzb3JEzPPBtdoAVAem7dVqy8mRUNkQdCh71bdmmLFoBzTD582+E4VgcTPGFCSuQLGkwpCxLCrqnx97JwKDUIwvuqxWPUgQaVgVvc03ClS1KjyyV/dYbPLC3xvC57LzVuA0hGJrYKWelrDPEEAd6+yfaEMV9f6bxDyBPl8o6ucgR3tJzbbeY4Yp7gjxk9GZEz4cecvj29GUBbtGN2x7emDXXj83xWmSqTl0p9goDmdYX03V/cf67BfQa7Fz0aIIracNeSmzUKIJw7EjpTn32d6IfB8uerd1B8MQxCmYxEY0NAejTlXpXnmnqXATpPQq3KU0VTME9ytfYB7vo1pAlRnfvldxGbIQObFknr1ndv1grZ0rbeQj05dn+0qpcIM1WLmUyLOKDW4ZUwNrE8TDKuc3cVL7oz/doaIU0qC+mlxxbg/f5fwIy6v9OB6pq7WIZyVoKF/hZikG1fpx+lmdeelOmtI0N1oONO75s=
  - secure: P705arAE90NYbvPSYI7tRr9BSo1+/k/HYoydtPUqCKO77XZ3cavHMkJi2FkWHlC/6xk3sr3Rf7RM48vlJlKK7o+ET05iRWzA+2Hy1TX68nWgK/LH65/1weggY4fIA4KrJLDMte8+Un+rAVrGNbQu4HzxClXjfGIB6dgCAfglRE2A7JEjUc8QVEpiIP5JQVBKLOiKoyGGs/wU5ieyARegi4OaJOSdsb3eqXeNyMXXUcAy+6A47oIvvGsTOOcxSzL7szrwDY59guGVQWlCbXRviS14tmxwmq7YjWH7BDzVdzARvXNA6k/lRDY440IqVEQo7vYIHzMNB8Y5FLJ7UMgWRxHWsHfRVVi2+zxQwLlpua9NRHJAHVtx+6Ol41axeCSeD/nsRePG1P2fglCvMamD+JbZUAOOP35yJWALrj6tX1sAImBsX1QtwbI6FEpDR7D/PTP7LFEMh7PyK13XcoRizGrpnhiSCFH5WZ/xTHlFsp9L0K1RpEDdbRhfxwIHPudt3x00/6hO9Ge74UFACK20mdF10yVOWcL/UqgcQMSja8A5VEKYNGXr0j+Zt3if6hA3BUlrkF0yJc+ZabHwrW81zPeXgfK0W8K+EkSO5RPiJrk93ENT7cwS8CPW/wK0d+gtHYRXfj68JnvLS5JO3xvPo+k6ci6pSaaOtQlRT1xEW0k=
